sudo: required
services:
- docker
env:
  global:
  - secure: 5IXUIJjZX2Qjzs3c4zciD1ytlv+IvSgnuCmsJ3gJ2P9Ge0n9gzRKPtnHumnWU5Xc5DP56Bda9zF/DacbqXT9aPWLP76It1ONyD9tPwK7khyyj/k760I/+6XUthgo8MwOLB22sz4y7qQvFZmzrFbn2KFb0p5FkadDcvkS+YJ316OXoVz8gauHS3lImmXRUdeVl0BZkYUS2DM3Ka+WW5m5sgE8eeePK6/gq1H/0/oylUoz62T44hcQcUmxSNB8Q437CTXzGjEqoXAQkzJ1O8UvDtBuxrVmoMaqsMEFE8iDKNWv+kb/rjfGi/tM3hX6oFenTAQqeXdtt4/bgnqTmrRoJuMYFf8OmnQdApOMm/9T1jXs8q/iRSOT7G/eCMfK1bJFUVVLTHfvSDbjyICbtPV2oh+0GDeHP2RpWE5rtPw+vdFDwAusEdUcgBahfJkHCDIT68VB93Bztgtik02yJHqigQ4NWtTnJg0PD14Q0bjRGH07nioJ+Gejg8LTaLO4jlZqXPY6fAcbMPQ7WBjqUaVbY3XivBojyWLHE2MNA1+UuugTqMK/cQ+ECi2aSVbjakYJH6SUIk0KLJWt5V0C9ImVQPoQJwtxE0rwsgwrY8Dmdvp/B2/IfFQISM8uWRn1FqdX2cTEp/nHG4v0wnMCglKDw6K22iaW8cOV7NSjzFeUGu0=
  - secure: j2eKKfkYKq74nrgvPucLwOMK5xVqy3DsT1uNilf+QfAXVXRYE66a10eu94YwpAq05JbD+OkULBwSqkGiDgkHKosgFHuF7QVFZRiHJQB1zWeQR1n59BCUKkikBjeKBFfoekoNaVtt4qUc33aBmkpuCTIaskO0magNL131iXnrUiH7p9IO2km64nyh8EhH47paq1ZOOm07Itp0YLMd++Locq0DWvlRcTI3e6Kg/8K/XneoGVhFGU4eqitqQD0Jj0fOkcVR5pzZ7OZjv+R+IZuqdiSIV4Rj9oLWGDqUnpRnyLvfCxoRyzrr+Mo4/iu+aNw8xorJy5dl6NMcpYdHZTxEe+9RoxTf6Dv2KjTcbz8dSk8VvQjM74pp6/R4uBgMLt7olvkTyQxbjyf8gWhrxDNmeY5JVRCfMOtjGDs+BDlUmA6hG1SBLrz2GgjsxQv6EOC0+FnCsMQ5d3N9EJ4c9dOiiPWgnbfU85RnkKUDphG6xlTGdeXcySvIFH89zsRRiz6vI9IcDSCeZeIMVRfZofXnrplYAXkCnSZiEh3tuGso3yClCtRMztYd5zCDVJk6QEj+PrgW/VlgW3w7BYCLF1WYBaECV0va0MhfuJDcD//csdsqQ69vUjOPqIbEVjp1DYu4rIE7MVrLL3vOULW1JRJv1VulykzRB9wnhzBkWQ1UaSg=
  - secure: MZE/sd31hoiWbnFT+wP+MsaGpZYzWG7cRfnjPLF9I9y07TDr4lxoLqs0zM39LWy+4/F3IVrSuHB6pAZvhdkZ23qbHVa9sLW+ykpWf2zbY2Ca7gQ/gYUGVwjLbK3XPZTSxV8k+jKl7/XD5fvq0hPvbaLToA5FeJEDtbjuI1iU6xUjdSMGCRSNhGZ43NJJP6CQJcrM6U47gSlJhXyptmzQGBzVkQL0D3sktLAj+ufavK1jDLuExWaJRipwk52GaDq6yXDAqa6bz/C6n4vQKCfO4wgJEje0aUuCvBpHMZS6tGloVwN7PgVrn/CtcHXxAJpkgb/gtN4n29Gi5EvWPP4ZKOVM/U/KcNM06OVsxoLPSlD5ww1H4xTI4w5w0Zcl4Njmsnhp2Am+b4MIFid52G/zKChrYMbOzESzsJfacbs56o/LpRenD0jJR9nJSfGRKOFdKifwletvwKh4lD4p8x2NjKHd/ILdVkLgNZQIjPJLSpKaWM+fO0u80l+/0OGjf7DMXxPAjX2XVrBxAgNMeB+UUHCwdfffk12aBjatHGUwFFpqNLXMpqK3fY983/n/6YpAL2eVObiaR6vIQeRt4MbvYc/WVV32pmyTm33g0ybnPvnrZ4YwydD0SLKtSdxa7c5haxoNhwU8BKqc7L+YZkKhVZS0SgxcvXtlBB2mVViFyNs=
install: true
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then exit 0; fi
- export COMMIT=`git rev-parse --short $(git ls-remote https://github.com/atech/postal.git refs/heads/master | awk '{print $1}')`
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=alinuxninja/postal
- export TAG=`echo $TRAVIS_BRANCH;`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker push $REPO
branches:
  except:
  - master
