sudo: required
services:
- docker
env:
  global:
  - secure: qE7v3em56NkEjk0cx2lK7ksPEwLwIXZgyq92p2tfut98t6Ra+/pvnaAirDALDbDDTJ/NbK6pL1y4n0SPAONdyY5k7O1TuWqPJc8Ml0+6+h/vudXOTikEh4VzZQBxmGeftjE1wFly7pO5YrtXgKVHeq6jpAR9YKnBzshzimutlT+pmyeWS3fFUbiVaBqJ339UW+YNpw8+0YtWKrYH32IiwqWFGTACW9VZNHLecxrBKvuDub3YLeLhIMTEdNVWinepAnHdBmenexstBXDAvusQNQEdZ1cOKrHob9SXIGVQsLOvsw35cAKUn0Evf3yGDs5XWDdSOzC2SoBwrM0fqnZ3CqVMTySjMoGv8+qIp88i4YmO51GvtspFxviIZf6bDAS3ppSQI31Vgnt3z1Yjflx4xQZ8tvLNSWKcTEolXzQ/9dges1aZKDkRx8Q6nD3hBOE3PdPucsIA+HGDdL3hAbgKHI2Kql7uOQskid1Ut9xhOudcI3SIyK7UQrt9VHDJHsNHiBy9OgEoAt26Q0kmA/BqHXLm5lRrFb0FR+Acqt6n2qHtBAW1lAawC6ChG4jLjS9HkHf6Ic2LEFyMUICdYSd7EzB7nthxlQt4SWTW8ejrUIgsafRSqPw+FWM6lmqMnQbSNJ5p6jBT4jszon2X3HWTDkPb0lOr6siLvNlyVZGIFwI=
  - secure: D5f9DHi0V4TWD5Bz0BmnQgVTbroG9rCU0jn6HeimgHgVRviJPx2JQehDDdzvShvZT9qyUUFXc7byOKL6m7RvjRNhKXZF31hf7yy60G0gHiNjglZzHI3houD5bQqTu7Xw8noImGaOuxqOlz7uwhQ/SQWdIdBAxjKg8DXHd3qUdKpdQXjIRdtDN0sSVFY33PgWYRbXV/+9L+ubrjuHie4BcVImxj721ZM/VxrePYwUmSr1vAib87Nb+L63Jv7D99HDgKjOkrdaqCuXiHI4GWYG2OYyQyDeJhR0GVH3+7P0Q39eQ4cer2I2F/3VJZFY3qijrr4a136UpcUNGrcyn6xwq1esl61EzL6ycRcUbnyIQh6ruueUHnX4LECX/IXqFrwxGj8qysid6r3rwOxQFl0sqBjaR6+0BeSnef+SgvJiEfr14Nr6UyF2byjrs3zdobsTmRK/9Ql7G6JgYYKDok1vcSTT3+YYcpGAvloRs7mLS/5Zb462qp8/I2z6qvXOYwyAeEvtAxVH0Y72MuVkjv9PFIVuhJB2eMzocC16bD4cMn9bNO0V7emuf3kPKZ/DHXO4K+JUYG6pd0/VaOhlod5m8GjncYC/ULXlg2MAeTzOuzCyFfREFPlqqbcpWsO0vlJxLVbx0I+6fqFVd42SsS6dADBEIjBcbCT7TJTMobywtxI=
  - secure: XaBdIEAPpFbkIdzX/avP8ykRH6UkKAbAmK3nDDFRjzb/FYuAWh5J44968V0oM5Sew0+g1MPryjbFM1vQp8eYVHQvpOYrdtaCQdQ88WLCmvgSbWCrg5853OBqN7aUBQ2KiKhmyWTl8XgbLB40oghc8eIL7mTajLz4XBpCF4B5f1F4Hts0D0quXNhxLfO1nnHLEx4R5lHlC6O4h1U7UHumdwXl3R8A+pGFB3CbuLeY8f0l69C1criRQdZC7PZIYAYkv+Td1pyoV1hYj+wNobtlvE61p8AiZUPSo3N7l+0CMwW/fe6NX9MFpvRsZqed9Hb+m7rAhuwxswUm3fioL7O+7jsAq6ZJp/qxz02jKtkokb2PPekY7W4IVJxah5lstNhAJOs5tYRw41i98x+873fbo+t1RI1ZxaogxGbVQuAxwOPVd7TTnU4EBClYPGPMPxbP7+dKc0waOQn6/TaLgKQurPHXc1qObLiNZ7xYxCbooL7vtBMoGBt0/FhJKxm8SvicaJ7q+Xk9KhYggYLfqRs6Bsb+F/yGVmOa7td71qn7Z5UYp0Rc7LCVo70OLq18FkNrhd6zkN50ZluoiP0KLT3sK994fRjonS1+0/3BYO5zyss87sOQpEWk/S1d2LGeM+g2nocrdHnFRcsZ5/+adog2gZZXrcP6EYH6dLL+p0V11fs=
install: true
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then exit 0; fi
- export COMMIT=`git rev-parse --short $(git ls-remote https://github.com/atech/postal.git refs/heads/master | awk '{print $1}')`
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=alinuxninja/postal
- export TAG=`echo $TRAVIS_BRANCH;`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker push $REPO
branches:
  except:
    - master
