sudo: required
services:
- docker
env:
  global:
  - secure: pystowtNN2YS7gWL1F9aXEiCHLT7bVx1rofmE4bVml+rkoYM6ajPnvM/iNjCUUtIezcc28OOQgwpGpuZqnyNo1NM6BKo0CKax2/Y2RbxwXmUA3B7O/3Pnv886WAzYlL5T5kIfargMVhrcaSKoErGk39o6io9I4hG589hd6iT9ReOwqSgr6s8RnfXyyz3lGmR7uYZK0MSugiEhgoCxuGswyYVVBVZqabS5BPt2kmWEFKzoTiSAFFube6tOAZtueYcLXlN0Pw4GOMOLOwSJl1g2hjLQVkrjWlO3mBTaFVMixSfr2Fr21Jrdp22PRJ4DsAFiLQK9dPqP3tYtjIIScai+2Ol47GplT5JY9W47nZL3k1hJSm5HsbzwB0A+SDcUivObPBGv3d0XeUzB0Ozv9z7vznJVdBRihNQ6bzNmoMDRVkSRCsav2Fo7x0JryjQAJx0NrUHGYJ13i/uyY9wVVB1q1mazV+rphyvlaWNRYx90tMAvV3Rg8GmSPinWe5BBh486ETvnm894fsz5XES8xWMj3Au0BpRJ67FjcfxkQs2/WRHOMjHCiB+OFzeV0JP6EtpcOVETQDipbmxqX6lenlCCPE9D9hf/pp2t+EWfiilAUez9nx6mLpYbSndEwkH5yF/8CJe342dLm6niDKWOwgkgJ9hFDBgzdEDHnsbe01/BoU=
  - secure: DpL8mHYpE2Wv0W640UFplG7dOmtm04F5YcxyPqDLWrNY8VB1P29IeFUxJITWP6wa0OLN7kN7ASJD4Hm21Zn70pTz5mnzHFC57chu+K6V95nuPl3IrsZg0TLAEDqiQZoEXnm9ZgL4Sldk7ITwH5a2Bj2ciWEsXgu3RNaOleRbVsKxFdC89SLaKXsVWY4qI6k2HmccA5rlQXwjXUYk4d58OFt2ADmknOJ9my1dHFOLuHOOiY0T/wYRPnSXulDfD40HMtDaYnXhYZFCwKKUVDHGjjmABKJcuaMxsUn+gewzmKWTnQe6KmB62S1wmtz6nTBTY4itW1yOIYEcunmo2Nhl8oStuEumB09ASU1Ab4muxxnVjmeS6aSRaU9ej2dA/AIyC+C3qb1TALel8FDwBuqhBLnPcljDJB+8U1q7IQ5PcjSfNv3hq0rx0rKDyoA/Mv5Pt0XEkH1X84hTJAPzzTEsQqsdkls9+xctyITbDgdTcK/+NABW9l4aVOjFg/eU4TWLSJS6OwGM/CDr1g32oJdn5ylAodSaCya+Y/AHZilFwCdfsJ8oDDj+j8bHxXFA+iFTY0aGUMvxuSLeJ2ixdVXmk3NQYbiU0fuABgucUcmpwLKd57Dukgmbm0iFDMl/o4+xmakwQTZshKYxbo2F2KZbA7/McHVt6YM/UZuBT1WVdZM=
install: true
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then exit 0; fi
- export COMMIT=`git rev-parse --short $(git ls-remote https://github.com/atech/postal.git
  refs/heads/master | awk '{print $1}')`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=alinuxninja/postal
- export TAG=`echo $TRAVIS_BRANCH;`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker push $REPO
branches:
  except:
  - master
